///* Generated By:JavaCC: Do not edit this line. PNparserConstants.java */
//package hk.ust.lpxz.petri.graph.GadaraSupport.parser;
//
//public interface PNparserConstants {
//
//  int EOF = 0;
//  int EQUALS = 5;
//  int ATTRSEP = 6;
//  int DECLSEP = 7;
//  int RBRACE = 8;
//  int LBRACE = 9;
//  int PLACECOMMON = 10;
//  int PLACEENTRY = 11;
//  int PLACEEXIT = 12;
//  int PLACERESOURCE = 13;
//  int PLACECONTROL = 14;
//  int TRANSITION = 15;
//  int ARCLOCAL = 16;
//  int ARCCALL = 17;
//  int ARCRETURN = 18;
//  int ARCFROMRESOURCE = 19;
//  int ARCTORESOURCE = 20;
//  int ARCFROMCONTROLLER = 21;
//  int ARCTOCONTROLLER = 22;
//  int PETRIMETHOD = 23;
//  int PETRICS = 24;
//  int VIOLATION = 25;
//  int ARROW = 26;
//  int STMTATTR = 27;
//  int TOKENATTR = 28;
//  int ENCLOSINGMATTR = 29;
//  int CONTROLLABLEATTR = 30;
//  int OBSERVABLEATTR = 31;
//  int WEIGHTATTR = 32;
//  int CTREDPLACE = 33;
//  int OBSEDPLACES = 34;
//  int METHODSIGATTR = 35;
//  int ENTRYATTR = 36;
//  int EXITATTR = 37;
//  int PPLACEATTR = 38;
//  int CPLACEATTR = 39;
//  int RPLACEATTR = 40;
//  int RESOURCEATTR = 41;
//  int PLACESATTR = 42;
//  int TRUE = 43;
//  int FALSE = 44;
//  int VARNAME = 45;
//  int INTEGER = 46;
//
//  int DEFAULT = 0;
//
//  String[] tokenImage = {
//    "<EOF>",
//    "\" \"",
//    "\"\\t\"",
//    "\"\\r\"",
//    "\"\\n\"",
//    "\"=\"",
//    "\",\"",
//    "\";\"",
//    "\"}\"",
//    "\"{\"",
//    "\"PlaceCommonLocal\"",
//    "\"PlaceMethodEntry\"",
//    "\"PlaceMethodExit\"",
//    "\"PlaceResource\"",
//    "\"PlaceControl\"",
//    "\"Transition\"",
//    "\"ArcLocal\"",
//    "\"ArcCall\"",
//    "\"ArcReturn\"",
//    "\"ArcFromResource\"",
//    "\"ArcToResource\"",
//    "\"ArcFromController\"",
//    "\"ArcToController\"",
//    "\"PetriMethod\"",
//    "\"PetriCS\"",
//    "\"Violation\"",
//    "\"->\"",
//    "\"stmt\"",
//    "\"token\"",
//    "\"enclosingPM\"",
//    "\"controllable\"",
//    "\"observable\"",
//    "\"weight\"",
//    "\"ctredplace\"",
//    "\"obsedplaces\"",
//    "\"methodsig\"",
//    "\"entry\"",
//    "\"exit\"",
//    "\"pplace\"",
//    "\"cplace\"",
//    "\"rplace\"",
//    "\"resource\"",
//    "\"places\"",
//    "\"true\"",
//    "\"false\"",
//    "<VARNAME>",
//    "<INTEGER>",
//  };
//
//}
